### ISSUE TITLE
java.io.FileNotFoundException: .onnx file not found

### ISSUE THREAD

**Issue by chenxin4839** [litongjava/ai-server#4]
项目启动报文件未找到异常
java.io.FileNotFoundException: .onnx file not found in: C:\Users\Administrator\.djl.ai\cache\repo\model\undefined\ai\djl\localmodelzoo\ff986e01c27f72ffaa13a437c93668d56ff025e5
	at ai.djl.onnxruntime.engine.OrtModel.load(OrtModel.java:80)
	at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:166)
	at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:172)
	at ai.djl.repository.zoo.ModelZoo.loadModel(ModelZoo.java:141)
	at com.litongjava.ai.djl.paddle.ocr.v4.PaddlePaddleOCRV4.<init>(PaddlePaddleOCRV4.java:46)
	at com.litongjava.ai.djl.paddle.ocr.v4.PaddlePaddleOCRV4.<clinit>(PaddlePaddleOCRV4.java:32)
	at com.litongjava.ai.server.padddle.ocr.config.PaddleOcrConfig.initOcr(PaddleOcrConfig.java:16)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.litongjava.jfinal.aop.process.ConfigurationAnnotaionProcess.processConfigInitialization(ConfigurationAnnotaionProcess.java:133)
	at com.litongjava.jfinal.aop.process.ConfigurationAnnotaionProcess.processConfiguration(ConfigurationAnnotaionProcess.java:80)
	at com.litongjava.jfinal.aop.process.BeforeStartConfigurationProcess.process(BeforeStartConfigurationProcess.java:55)
	at com.litongjava.tio.boot.context.TioApplicationContext.processBeforeStartConfiguration(TioApplicationContext.java:266)
	at com.litongjava.tio.boot.context.TioApplicationContext.run(TioApplicationContext.java:94)
	at com.litongjava.tio.boot.TioApplication.run(TioApplication.java:19)
	at com.litongjava.tio.boot.TioApplication.run(TioApplication.java:12)
	at com.litongjava.ai.server.padddle.ocr.PaddleOcrServer.main(PaddleOcrServer.java:24)
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.litongjava.jfinal.aop.process.ConfigurationAnnotaionProcess.processConfigInitialization(ConfigurationAnnotaionProcess.java:133)
	at com.litongjava.jfinal.aop.process.ConfigurationAnnotaionProcess.processConfiguration(ConfigurationAnnotaionProcess.java:80)
	at com.litongjava.jfinal.aop.process.BeforeStartConfigurationProcess.process(BeforeStartConfigurationProcess.java:55)
	at com.litongjava.tio.boot.context.TioApplicationContext.processBeforeStartConfiguration(TioApplicationContext.java:266)
	at com.litongjava.tio.boot.context.TioApplicationContext.run(TioApplicationContext.java:94)
	at com.litongjava.tio.boot.TioApplication.run(TioApplication.java:19)
	at com.litongjava.tio.boot.TioApplication.run(TioApplication.java:12)
	at com.litongjava.ai.server.padddle.ocr.PaddleOcrServer.main(PaddleOcrServer.java:24)
Caused by: java.lang.ExceptionInInitializerError
	at com.litongjava.ai.server.padddle.ocr.config.PaddleOcrConfig.initOcr(PaddleOcrConfig.java:16)
	... 12 more
Caused by: java.lang.NullPointerException: Cannot invoke "ai.djl.repository.zoo.ZooModel.newPredictor()" because "detectionModel" is null
	at com.litongjava.ai.djl.paddle.ocr.v4.PaddlePaddleOCRV4.<init>(PaddlePaddleOCRV4.java:55)
	at com.litongjava.ai.djl.paddle.ocr.v4.PaddlePaddleOCRV4.<clinit>(PaddlePaddleOCRV4.java:32)
	... 13 more
java.net.BindException: Address already in use: bind
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.AsynchronousServerSocketChannelImpl.bind(AsynchronousServerSocketChannelImpl.java:164)
	at com.litongjava.tio.server.TioServer.start(TioServer.java:109)
	at com.litongjava.tio.boot.server.TioBootServer.start(TioBootServer.java:94)
	at com.litongjava.tio.boot.context.TioApplicationContext.configAndStartServer(TioApplicationContext.java:253)
	at com.litongjava.tio.boot.context.TioApplicationContext.run(TioApplicationContext.java:113)
	at com.litongjava.tio.boot.TioApplication.run(TioApplication.java:19)
	at com.litongjava.tio.boot.TioApplication.run(TioApplication.java:12)
	at com.litongjava.ai.server.padddle.ocr.PaddleOcrServer.main(PaddleOcrServer.java:24)

**Comment by litongjava** [comment]
应该是网络问题下载 文件失败了

**Comment by litongjava** [comment]
https://github.com/litongjava/ai-server/tree/main/rapid-ocr-server

试一下这个项目。不依赖djl
